services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./production.env
    ports:
      - "5000:3000"
    # depends_on:
    #   my-mongodb:
    #     condition: service_healthy
    volumes:
      - .:/code

  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27018:27017
    env_file:
      - ./production.env
    environment:
      - MONGO_INITDB_DATABASE=${test}
      - MONGO_INITDB_ROOT_USERNAME=${BD_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${BD_PASSWORD}

    # environment:
    #   - MONGO_INITDB_DATABASE=test
    #   - MONGO_INITDB_ROOT_USERNAME=admin 
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  redis:
    image: redis:4
    container_name: my-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mongodb:
  mongoconfig:
  redis_data:
